In [1]:
# Introduction
import numpy as np

In [4]:
vector_row = np.array([1,2,3])
print(vector_row)

[1 2 3]


In [7]:
vector_col = np.array([[1],
                       [2],
                       [3]])
print(vector_col)

[[1]
 [2]
 [3]]


In [8]:
# Matrix
normal_matrix = np.array([[1,2],[2,3],[4,5]])
print(normal_matrix)

[[1 2]
 [2 3]
 [4 5]]


In [9]:
# Sparse Matrix
sparse_matrix = np.array([[1,0],[0,0],[0,3]])
print(sparse_matrix)

[[1 0]
 [0 0]
 [0 3]]


In [11]:
# compressed sparse matrix(csr)
from scipy import sparse
sparse_matrix = np.array([[0,0,0,0,0,1,0,0,0,0,0],
                        [0,0,0,0,0,0,0,0,0,0,0],
                        [2,0,0,0,0,0,0,0,0,0,0],
                          [0,0,0,0,0,0,0,0,0,0,1]
                         ])
print(sparse_matrix)
sparse_matrix = sparse.csr_matrix(sparse_matrix)
print(sparse_matrix)
# Other sparse matrices are :
#         compressed sparse column, 
#         list of lists, and 
#         dictionary of keys.

[[0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1]]
  (0, 5)	1
  (2, 0)	2
  (3, 10)	1


In [2]:
# Selecting elements
vector = np.array([1,2,3,4,5])
matrix = np.array([[1,2,3,4,5],
                  [11,12,13,14,15],
                  [21,22,23,24,25]])
print("Selecting all elements from matrix\n",matrix,"\n and from vector\n",vector)
print("Being Selective")
print(vector[2])
print(matrix[1,4])
print(vector[1:4])
print(matrix[:2,:]) # first two rows and all cols
print(matrix[:-2,:]) # first row and all cols
print(matrix[:,2:]) # all rows and all cols from 3rd

Selecting all elements from matrix
 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]] 
 and from vector
 [1 2 3 4 5]
Being Selective
3
15
[2 3 4]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[[1 2 3 4 5]]
[[ 3  4  5]
 [13 14 15]
 [23 24 25]]


In [28]:
# Describing a matrix
matrix = np.array([[1,2,3,4,5],
                  [11,12,13,14,15],
                  [21,22,23,24,25]])
print(matrix.shape) 
print(matrix.size)
print(matrix.ndim) # number of dimensions

(3, 5)
15
2


In [32]:
# Arithmetic Operations
matrix = np.array([[1,2,3,4,5],
                  [11,12,13,14,15],
                  [21,22,23,24,25]])
add_100 = lambda i : i + 100
vectorized_add_100 = np.vectorize(add_100)
print(vectorized_add_100(matrix))

# OR
print(matrix+100)

# OR
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        matrix[i,j] += 100

print(matrix)


[[101 102 103 104 105]
 [111 112 113 114 115]
 [121 122 123 124 125]]
[[101 102 103 104 105]
 [111 112 113 114 115]
 [121 122 123 124 125]]
[[101 102 103 104 105]
 [111 112 113 114 115]
 [121 122 123 124 125]]


In [9]:
# Max and Min
print("Maximum element ",np.max(vector))
print("Minimum element ",np.min(vector))
print("Maximum element ",np.max(matrix))
print("Minimum element ",np.min(matrix))
print("Maximum element in each col ",np.max(matrix, axis = 0)) # axis 0 is col
print("Maximum element in each row ",np.max(matrix, axis = 1))
print("Minimum element in each row ",np.min(matrix, axis = 1)) # axis 1 is row
print("Minimum element in each col ",np.min(matrix, axis = 0))

Maximum element  5
Minimum element  1
Maximum element  25
Minimum element  1
Maximum element in each col  [21 22 23 24 25]
Maximum element in each row  [ 5 15 25]
Minimum element in each row  [ 1 11 21]
Minimum element in each col  [1 2 3 4 5]


In [10]:
# Average, Variance, Standard Deviation
print(np.mean(matrix))
print(np.var(matrix))
print(np.std(matrix))

13.0
68.66666666666667
8.286535263104035


In [13]:
# Reshaping a matrix
print(matrix)
print(matrix.reshape(5,3))
print(matrix.shape) # reshaped but not assigned
print(matrix.reshape(-1,1)) # -1 in row field indicates as many rows as possible
print(matrix.shape) # reshaped but not assigned

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
[[ 1  2  3]
 [ 4  5 11]
 [12 13 14]
 [15 21 22]
 [23 24 25]]
(3, 5)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [11]
 [12]
 [13]
 [14]
 [15]
 [21]
 [22]
 [23]
 [24]
 [25]]
(3, 5)


In [24]:
# Transpose a matrix
print(matrix)
print(matrix.shape)
print(matrix.T)
print((matrix.T).shape)
print(vector)
print(vector.T) # A vector doesnot transpose
print(np.array([vector]).T) # A technique to transpose a vector

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
(3, 5)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]]
(5, 3)
[1 2 3 4 5]
[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [26]:
# Flattening a matrix
print(matrix)
print(matrix.flatten())

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
[ 1  2  3  4  5 11 12 13 14 15 21 22 23 24 25]


In [31]:
# Finding Matrix Rank, determinant
matrix = np.array([1,2,3,4,5,6,7,8,9])
matrix = matrix.reshape(3,3)
print(matrix)
print(np.linalg.matrix_rank(matrix))
print(np.linalg.det(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
-9.51619735392994e-16


In [36]:
# getting the diagonal of a matrix and trace(sum of diagonal elements)
print(matrix)
print(matrix.diagonal())
print(matrix.trace())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
15


In [38]:
# Finding the Eigen Values and Eigen Vectors
print(matrix)
matrix_eigen_value, matrix_eigen_vector = np.linalg.eig(matrix)
print(matrix_eigen_value)
print(matrix_eigen_vector)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [40]:
# Calculating dot products or multiplying two matrices
print(matrix)
print(np.dot(matrix, matrix))
print(matrix @ matrix) # From Python > 3.5, @ is used as an operator to perform a dot operation

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [43]:
# Adding and Subtracting two matrices
print(matrix)
print(np.add(matrix, matrix))
print(np.subtract(matrix, matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [45]:
# Inverting a matrix
print(matrix)
print(np.linalg.inv(matrix)) # Invertion can be done only on a square matrix

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [55]:
# Generatin Random Numbers
np.random.seed(8) # Every time it generates the same random sequence for the seed specified
matrix = np.array(np.random.random(9))
print(matrix)
np.random.seed(0)
matrix = np.array(np.random.randint(0,500,9)) # Generating 9 random integers in a range (0,500)
print(matrix)
matrix = np.array(np.random.normal(0.0,1.0,9)) # Draw 9 numbers from a normal distribution with mean = 0.0 and std_dev = 1.0
print(matrix)
matrix = np.array(np.random.logistic(0.0,1.0,9)) # Draw 9 numbers from a logistic distribution with mean 0.0 and scale of 1.0
print(matrix)
matrix = np.array(np.random.uniform(0.0,1.0,9)) # Draw 9 numbers greater than 0.0 and less than = 1.0
print(matrix)

[0.8734294  0.96854066 0.86919454 0.53085569 0.23272833 0.0113988
 0.43046882 0.40235136 0.52267467]
[172  47 117 192 323 251 195 359   9]
[-1.42232584  1.52006949 -0.29139398 -0.13309028 -0.1730696  -1.76165167
 -0.08767307  1.36687937  1.1253141 ]
[-0.67491949  0.61101311 -0.53976806  3.10638027 -1.81237956  1.9017305
 -0.10566603  1.39199631  0.08195576]
[0.67887953 0.72063265 0.58201979 0.53737323 0.75861562 0.10590761
 0.47360042 0.18633234 0.73691818]
